konveyor-ecosystem/kantra-cli-tests

- tests/test_analysis.py
- utils/report.py
This PR adds the logic to calculate the story points that should be displayed in the report by using the analysis' output.
@sshveta could you review this PR please? Thanks!
> [RFR] add story points assertion

- tests/test_advanced_options.py
Solves [MTA-1275](https://issues.redhat.com/browse/MTA-1275)
@sshveta could you please review this PR please?
> [RFR] Add skip report test

- data/xml/javax-package-custom-target.windup.xml
- data/yaml/javax-package-custom.windup.yaml
- tests/test_advanced_options.py
- utils/report.py
Solves [MTA-1276](https://issues.redhat.com/browse/MTA-1276)
Automates Polarion TC [MTA-374](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-374)
This test will fail right now due to bug [MTA-1305](https://issues.redhat.com/browse/MTA-1305)
@sshveta could you please review this PR? Thanks!
> [RFR] Add custom rules test

- requirements.txt
- tests/test_transform.py
- utils/constants.py
Solves [MTA-1278](https://issues.redhat.com/browse/MTA-1278)
Automates TC [MTA-376](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-376)
@sshveta could you please review this PR? Thanks!
> [RFR] Add rules transformation test

- .github/workflows/mac.yaml
- tests/test_advanced_options.py
Solves [MTA-1399](https://issues.redhat.com/browse/MTA-1399)
This workflow will install the latest kantra version, then fetch this repository and run one analysis test and all the other tests that don't have "bug" in their name.
[Example run](https://github.com/abrugaro/kantra-cli-tests/actions/runs/6971226340)
Note: Please squash the commits before merging this PR.
> [RFR] Mac workflow

- tests/test_common_options.py
Solves [MTA-2114](https://issues.redhat.com/browse/MTA-2114) & [MTA-2115](https://issues.redhat.com/browse/MTA-2115) by automating Polarion Tcs [472](https://polarion.engineering.redhat.com/polarion/redirect/project/MTAPathfinder/workitem?id=MTA-472) & [488](https://polarion.engineering.redhat.com/polarion/redirect/project/MTAPathfinder/workitem?id=MTA-488)
@sshveta could you please review this PR? Thanks!
> [RFR] Automate sources and targets duplicates check

- tests/test_common_options.py
> [RFR] Update targets test

- data/analysis.json
- data/applications/camel-cbr/.classpath
- data/applications/camel-cbr/.project
- data/applications/camel-cbr/.settings/org.eclipse.core.resources.prefs
- data/applications/camel-cbr/.settings/org.eclipse.jdt.apt.core.prefs
- data/applications/camel-cbr/.settings/org.eclipse.jdt.core.prefs
- data/applications/camel-cbr/.settings/org.eclipse.m2e.core.prefs
- data/applications/camel-cbr/README.md
- data/applications/camel-cbr/pom.xml
- data/applications/camel-cbr/src/main/fuse/data/order1.xml
- data/applications/camel-cbr/src/main/fuse/data/order2.xml
- data/applications/camel-cbr/src/main/fuse/data/order3.xml
- data/applications/camel-cbr/src/main/fuse/data/order4.xml
- data/applications/camel-cbr/src/main/fuse/data/order5.xml
- data/applications/camel-cbr/src/main/resources/OSGI-INF/blueprint/cbr.xml
Implements [MTA-2244](https://issues.redhat.com/browse/MTA-2244)
> [RFR] Added kafka fuse test from ticket MTA-2244

- tests/test_common_options.py
- tests/test_negative.py
Updated expected error message when target is unknown
Added verbose error message when test is failing
> [RFR] Updated expected error message when target is unknown

- tests/test_advanced_options.py
- utils/command.py
- utils/report.py
Added bulk analysis
Slightly refactored command file to add `--bulk` usage when needed
Added report removal function to report file
> [RFR] Adding bulk analysis

- tests/test_advanced_options.py
- utils/report.py
> [RFR] Added final validations for bulk analysis test

- tests/analysis/java/test_selective_java_provider.py
Resolves https://issues.redhat.com/browse/MTA-3178 
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-cli-tests-runner/125/console)
> [RFR] Automate Java Provider

- data/yaml/01-javax-package-custom-target.windup.yaml
- tests/analysis/java/test_selective_java_provider.py
Resolves https://issues.redhat.com/browse/MTA-3373 
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-cli-tests-runner/146/console)
> [RFR][TA] Verify Java analysis with custom rule

- data/yaml/tackle-dependency-custom-rule.yaml
- tests/analysis/java/test_java_analysis.py
- tests/test_advanced_options.py
Solves [MTA-4013](https://issues.redhat.com/browse/MTA-4013) by automating bug [MTA-3863](https://issues.redhat.com/browse/MTA-3863).
Since the bug is not fixed, the test will fail. I marked it and will unmark once the bug is resolved
> :sparkles: Automate dependency rule assertion

- tests/analysis/java/test_java_analysis.py
- tests/test_advanced_options.py
- tests/test_negative.py
- utils/common.py
This PR brings ability to run tests both in container and container-less (local) mode
> [RFR] Parametrized local run for java tests

- .github/workflows/mac.yaml
- .github/workflows/test-suite.yaml
- utils/output.py
- utils/test_output.py
This should get kantra CI green.
> Fix windows m2 path, disable arm64 Mac

- data/yaml/tackle-dependency-custom-rule.yaml
- tests/analysis/java/test_java_analysis.py
- tests/test_advanced_options.py
- utils/common.py
Resolves [MTA-5002](https://issues.redhat.com/browse/MTA-5002) by automating polarion TC 588 for bug [MTA-3169](https://issues.redhat.com/browse/MTA-3169)
This PR also removes the bug number of a different test now that it's been closed
> :sparkles: [RFR] Automate TC 588

- data/yaml/dotnet/example_rules/example.yaml
- tests/analysis/dotnet/test_dotnet_analysis.py
- utils/command.py
Resolves [MTA-2612](https://issues.redhat.com/browse/MTA-2612).
This PR modifies the .net custom rule to ensure it is triggered and verifies it
> :seedling: [RFR] Adapt dotnet test

- data/golang_analysis.json
Removed eap8 target as it is not relevant for golang test
> [RFR] Removed eap8 target from golang test

- tests/analysis/go/test_go_analysis.py
Forced container mode as now by default it tries to run locally
Removed irrelevant asserts
> [RFR] Forced container mode and removed not relevant validations

- data/expected/java_analysis/tackle-testapp-public-cloud-readiness/output.yaml
Similar change as in https://github.com/konveyor/go-konveyor-tests/pull/269
> Update tackle-testapp-public tags

- .github/workflows/nightly-main-release07.yaml
- README.md
Adding release-0.7 job.
Related to https://github.com/konveyor/ci/issues/91
> Update CI jobs for release-0.7

- tests/analysis/java/test_analysis.py
Marked bvp tests with bug https://github.com/konveyor/analyzer-lsp/issues/901
> :test_tube: [RFR] mark bug
